apps/products/urls.py
from django.urls import path
from .views import *

app_name = "products"

urlpatterns = [
    path("product/<slug:slug>/", product_detail, name="product_detail"),
]

apps/registries/urls.py
from django.urls import path
from .views import *

app_name = 'registries'

urlpatterns = [
    path('', registry_list, name='catalog'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.registries.urls')),
    path('', include('apps.products.urls')),
]

apps/products/models.py
from django.db import models
from django.utils.text import slugify
from apps.registries.models import Registry


class Product(models.Model):
    registry = models.ForeignKey(
        Registry, on_delete=models.CASCADE, related_name="products"
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, blank=True, null=True)
    description = models.TextField(blank=True)
    url = models.URLField()
    image_url = models.URLField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    is_reserved = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        # Si no hay slug, lo generamos automáticamente del nombre
        if not self.slug:
            base_slug = slugify(self.name)
            slug = base_slug
            # Aseguramos que sea único
            counter = 1
            while Product.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

apps/registries/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Registry(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="registries")
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True)
    is_public = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

apps/products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product

def product_detail(request, slug):
    # Busca el producto por slug, o lanza 404 si no existe
    product = get_object_or_404(Product, slug=slug)
    
    # Pasamos el producto al template
    context = {
        'product': product
    }
    return render(request, 'apps/products/product_detail.html', context)

apps/registries/views.py
from django.shortcuts import render, get_object_or_404
from .models import Registry


def registry_list(request):
    registry = get_object_or_404(Registry, is_public=True)

    products = registry.products.all()

    context = {
        "registry": registry,
        "products": products,
    }

    return render(request, "apps/registries/registry_list_product.html", context)

templates/apps/registries/registry_list_product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="container py-5">
    <div class="row">
      <div class="col-lg-3">
        <h1 class="h2 pb-4">Categorias</h1>
        <ul class="list-unstyled templatemo-accordion">
          <li class="pb-3">
            <a class="collapsed d-flex justify-content-between h3 text-decoration-none" href="#">
              Juguetes
              <i class="fa fa-fw fa-chevron-circle-down mt-1"></i>
            </a>
            <ul class="collapse show list-unstyled pl-3">
              <li>
                <a class="text-decoration-none" href="#">Carros</a>
              </li>
              <li>
                <a class="text-decoration-none" href="#">Barbies</a>
              </li>
            </ul>
          </li>
          <li class="pb-3">
            <a class="collapsed d-flex justify-content-between h3 text-decoration-none" href="#">
              Ropa
              <i class="pull-right fa fa-fw fa-chevron-circle-down mt-1"></i>
            </a>
            <ul id="collapseTwo" class="collapse list-unstyled pl-3">
              <li>
                <a class="text-decoration-none" href="#">Pulover</a>
              </li>
              <li>
                <a class="text-decoration-none" href="#">Pantalones</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>

      <div class="col-lg-9">
        <div class="row">
          <div class="col-md-6">
            <ul class="list-inline shop-top-menu pb-3 pt-1">
              <li class="list-inline-item">
                <a class="h3 text-dark text-decoration-none mr-3" href="#">Todo</a>
              </li>
              <li class="list-inline-item">
                <a class="h3 text-dark text-decoration-none mr-3" href="#">Hombre</a>
              </li>
              <li class="list-inline-item">
                <a class="h3 text-dark text-decoration-none" href="#">Mujer</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="row row-cols-3 g-4">
          {% for product in registry.products.all %}
            <div class="col">
              <div class="card mb-4 product-wap rounded-0 h-100 d-flex flex-column">
                <a class="card-link" href="{% url 'products:product_detail' product.slug %}">
                  <div class="card rounded-0">
                    <img class="card-img rounded-0 img-fluid" src="{{ product.image_url }}" alt="{{ product.name }}" />
                    <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center"></div>
                  </div>
                </a>
                <div class="card-body d-flex flex-column">
                  <span class="h3 text-decoration-none">{{ product.name }}</span>
                  <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                    <li>Categoria: Ropa</li>
                  </ul>
                  <p class="text-left mb-0 mt-auto">Precio: {{ product.price }}</p>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'layout/head.html' %}
  </head>
  <body>

    {% include "layout/header.html" %}
    {% include "layout/navbar.html" %}

    {% include "components/messages.html" %}

    {% block content %}
    {% endblock %}

    {% include 'layout/footer.html' %}
    {% include 'layout/scripts.html' %}

    {% block extra_js %}{% endblock %}

  </body>
</html>

templates/layout/footer.html
<!-- Start Footer -->
<footer class="bg-dark" id="tempaltemo_footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4 pt-5">
        <h2 class="h2 text-success border-bottom pb-3 border-light logo">Zay Shop</h2>
        <ul class="list-unstyled text-light footer-link-list">
          <li>
            <i class="fas fa-map-marker-alt fa-fw"></i>
            123 Consectetur at ligula 10660
          </li>
          <li>
            <i class="fa fa-phone fa-fw"></i>
            <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
          </li>
          <li>
            <i class="fa fa-envelope fa-fw"></i>
            <a class="text-decoration-none" href="mailto:info@company.com">info@company.com</a>
          </li>
        </ul>
      </div>

      <div class="col-md-4 pt-5">
        <h2 class="h2 text-light border-bottom pb-3 border-light">Products</h2>
        <ul class="list-unstyled text-light footer-link-list">
          <li>
            <a class="text-decoration-none" href="#">Luxury</a>
          </li>
          <li>
            <a class="text-decoration-none" href="#">Sport Wear</a>
          </li>
          <li>
            <a class="text-decoration-none" href="#">Men's Shoes</a>
          </li>
          <li>
            <a class="text-decoration-none" href="#">Women's Shoes</a>
          </li>
          <li>
            <a class="text-decoration-none" href="#">Popular Dress</a>
          </li>
          <li>
            <a class="text-decoration-none" href="#">Gym Accessories</a>
          </li>
          <li>
            <a class="text-decoration-none" href="#">Sport Shoes</a>
          </li>
        </ul>
      </div>

      <div class="col-md-4 pt-5">
        <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
        <ul class="list-unstyled text-light footer-link-list">
          <li>
            <a class="text-decoration-none" href="#">Home</a>
          </li>
          <li>
            <a class="text-decoration-none" href="#">About Us</a>
          </li>
          <li>
            <a class="text-decoration-none" href="#">Shop Locations</a>
          </li>
          <li>
            <a class="text-decoration-none" href="#">FAQs</a>
          </li>
          <li>
            <a class="text-decoration-none" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>

    <div class="row text-light mb-4">
      <div class="col-12 mb-3">
        <div class="w-100 my-3 border-top border-light"></div>
      </div>
      <div class="col-auto me-auto">
        <ul class="list-inline text-left footer-icons">
          <li class="list-inline-item border border-light rounded-circle text-center">
            <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
          </li>
          <li class="list-inline-item border border-light rounded-circle text-center">
            <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
          </li>
          <li class="list-inline-item border border-light rounded-circle text-center">
            <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="fab fa-twitter fa-lg fa-fw"></i></a>
          </li>
          <li class="list-inline-item border border-light rounded-circle text-center">
            <a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i class="fab fa-linkedin fa-lg fa-fw"></i></a>
          </li>
        </ul>
      </div>
      <div class="col-auto">
        <label class="sr-only" for="subscribeEmail">Email address</label>
        <div class="input-group mb-2">
          <input type="text" class="form-control bg-dark border-light" id="subscribeEmail" placeholder="Email address" />
          <div class="input-group-text btn-success text-light">Subscribe</div>
        </div>
      </div>
    </div>
  </div>

  <div class="w-100 bg-black py-3">
    <div class="container">
      <div class="row pt-2">
        <div class="col-12">
          <p class="text-left text-light">
            Copyright &copy; 2021 Company Name | Designed by <a rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/layout/head.html
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Welcome Baby{% endblock %}</title>

    <link rel="apple-touch-icon" href="assets/img/apple-icon.png">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    {% block extra_css %}{% endblock %}

templates/layout/header.html
<nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
    <div class="container text-light">
      <div class="w-100 d-flex justify-content-between">
        <!-- <div>
                <i class="fa fa-envelope mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                <i class="fa fa-phone mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
            </div>
            <div>
                <a class="text-light" href="https://fb.com/" target="_blank" rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://twitter.com/" target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin fa-sm fa-fw"></i></a>
            </div> -->
      </div>
    </div>
</nav>

templates/layout/navbar.html
<nav class="navbar navbar-expand-lg navbar-light shadow">
    <div class="container d-flex justify-content-between align-items-center">
        <a class="navbar-brand text-success logo h1 align-self-center" href="{% url 'registries:catalog' %}">
            Welcome Baby
        </a>
        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="align-self-center collapse navbar-collapse flex-fill d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
            <div class="flex-fill"></div>
            <div class="navbar align-self-center d-flex">
                <a class="nav-icon position-relative text-decoration-none" target="_blank" href="https://listado.mercadolibre.com.uy/bebe#D[A:bebe]">
                    <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
                    <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark"></span>
                </a>
            </div>
        </div>
    </div>
</nav>

templates/layout/scripts.html
{% load static %}
<script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/templatemo.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>